### ISSUE TITLE
What is the license agreement for this project

### ISSUE THREAD

**Issue by JohnnnyWang** [agourlay/hprof-slurp#83]
hi
This is a really amazing project, thanks to the authors for their works. I would like to ask, what is the license agreement for this project?
I hope to be okto fork this project and add some functions, such as: export analysis results(by bincode), support SQL search (like OQL).
thx

**Comment by agourlay** [comment]
Thank you for your interest in this project.

I will add a license to the project ASAP to clear up your concerns.

**Comment by JohnnnyWang** [comment]
Thans!

**Comment by agourlay** [comment]
FYI I have added a standard Apache 2 license https://github.com/agourlay/hprof-slurp/commit/d95174adfef280d7a74341d56e40ebde7f8ae31d
